# Скопируйте этот конфиг в ~/.aerospace.toml
# После этого вы можете редактировать ~/.aerospace.toml под себя

# Версия конфига для совместимости и депрекейтов
# Значение по умолчанию (если ключ опущен): config-version = 1
config-version = 2

# Команды, которые выполняются после запуска AeroSpace
# Доступные команды: https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []

exec-on-workspace-change = [
  "/bin/bash", "-lc",
  "/etc/profiles/per-user/vch/bin/sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE PREV_WORKSPACE=$AEROSPACE_PREV_WORKSPACE"
]

# Запускать AeroSpace при входе в систему
start-at-login = true

# Нормализация. См.: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# См.: https://nikitabobko.github.io/AeroSpace/guide#layouts
# 'accordion-padding' задаёт размер отступа в режиме accordion
# Можно установить 0, чтобы отключить отступы
accordion-padding = 30

# Возможные значения: tiles | accordion
default-root-container-layout = 'tiles'

# Возможные значения: horizontal | vertical | auto
# 'auto' означает:
#   - широкий монитор (шире, чем выше) → горизонтальная ориентация
#   - высокий монитор (выше, чем шире) → вертикальная ориентация
default-root-container-orientation = 'auto'

# Курсор мыши следует за фокусом при смене монитора
# Удалите этот параметр, если вам не нравится такое поведение
# См.: https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# См.: https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Значение по умолчанию (если ключ опущен): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Можно фактически отключить macOS-функцию «Скрыть приложение» (cmd-h)
# Полезно, если вы не используете эту функцию, но часто нажимаете cmd-h или cmd-alt-h
# См. также: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false

# Список рабочих пространств, которые должны оставаться активными,
# даже если в них нет окон и они не отображаются
# Эта версия конфига доступна только начиная с config-version = 2
# Значение по умолчанию (если ключ опущен): persistent-workspaces = []
persistent-workspaces = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]

# Колбэк, который запускается при каждом изменении режима биндингов
# См.: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# См.: https://nikitabobko.github.io/AeroSpace/commands#mode
on-mode-changed = []

# Возможные значения: qwerty | dvorak | colemak
# См.: https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
    preset = 'qwerty'

# Отступы между окнами (inner-*) и между окнами и краями монитора (outer-*)
# Возможные варианты:
# - Константа:     gaps.outer.top = 8
# - Для каждого монитора:
#   gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#   В этом примере 24 — значение по умолчанию, если монитор не совпал
#   Паттерн монитора такой же, как в 'workspace-to-monitor-force-assignment'
# См.:
# https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

# On-window-detected
# osascript -e 'id of app "VSCodium"'
[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = ["move-node-to-workspace 1"]
[[on-window-detected]]
if.app-id = "com.apple.Terminal"
run = ["move-node-to-workspace 1"]

[[on-window-detected]]
if.app-id = "app.zen-browser.zen"
run = ["move-node-to-workspace 2"]
[[on-window-detected]]
if.app-id = "com.apple.Safari"
run = ["move-node-to-workspace 2"]

[[on-window-detected]]
if.app-id = "md.obsidian"
run = ["move-node-to-workspace 3"]
[[on-window-detected]]
if.app-id = "com.apple.Notes"
run = ["move-node-to-workspace 3"]

[[on-window-detected]]
if.app-id = "com.vscodium"
run = ["move-node-to-workspace 4"]
[[on-window-detected]]
if.app-id = "com.apple.TextEdit"
run = ["move-node-to-workspace 4"]

[[on-window-detected]]
if.app-id = "us.zoom.xos"
run = ["move-node-to-workspace 5"]

[[on-window-detected]]
if.app-id = "com.apple.finder"
run = ["move-node-to-workspace 6"]

[[on-window-detected]]
if.app-id = "com.valvesoftware.steam"
run = ["move-node-to-workspace 7"]
[[on-window-detected]]
if.app-id = "com.valvesoftware.steam.helper"
run = ["move-node-to-workspace 7"]


# Объявление режима биндингов 'main'
# См.: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# Режим 'main' должен присутствовать всегда
# Значение по умолчанию (если ключ опущен): mode.main.binding = {}
[mode.main.binding]

    # Все возможные клавиши:
    # - Буквы:         a, b, c, ..., z
    # - Цифры:         0, 1, 2, ..., 9
    # - Цифры на numpad: keypad0, keypad1, ..., keypad9
    # - F-клавиши:     f1, f2, ..., f20
    # - Специальные:   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                  backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                  backspace, tab, pageUp, pageDown, home, end, forwardDelete,
    #                  sectionSign (только ISO / европейские клавиатуры)
    # - Спец. numpad:  keypadClear, keypadDecimalMark, keypadDivide, keypadEnter,
    #                  keypadEqual, keypadMinus, keypadMultiply, keypadPlus
    # - Стрелки:       left, down, up, right

    # Все возможные модификаторы: cmd, alt, ctrl, shift

    # Все возможные команды:
    # https://nikitabobko.github.io/AeroSpace/commands

    # См.: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
    # Можно раскомментировать, чтобы открыть Terminal по alt + enter (как в i3)
    # alt-enter = '''exec-and-forget osascript -e '
    # tell application "Terminal"
    #     do script
    #     activate
    # end tell'
    # '''

    # См.: https://nikitabobko.github.io/AeroSpace/commands#layout
    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#focus
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#move
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#resize
    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#workspace
    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
    alt-tab = 'workspace-back-and-forth'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # См.: https://nikitabobko.github.io/AeroSpace/commands#mode
    # semicolon == ;
    alt-shift-semicolon = 'mode service'

    alt-shift-r = ['layout tiles horizontal vertical', 'flatten-workspace-tree'] # сбросить раскладку
    alt-shift-f = 'layout floating tiling' # переключение между floating и tiling

# Объявление режима биндингов 'service'
# См.: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # сбросить раскладку
    f = ['layout floating tiling', 'mode main'] # переключение между floating и tiling
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky пока не поддерживается:
    # https://github.com/nikitabobko/AeroSpace/issues/2
    # s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
